name: Tntrun
version: '${project.version}'
main: eu.mineoase.tntrun.TNTRun
api-version: 1.18
website: https://mineoase.eu
softdepend: [Multiverse-Core]
depend: [Vault, Essentials]
commands:
  tntrun:
    description: test
  jumpboost:
    description: gives Player Jump Boost Potion 8 Seconds, Tier 2
  minefield:
    description: gives PLayer mineField Item
  spleef:
    description: gives PLayer spleef Shovel
  nohit:
    description: no Hit item
  c4:
    description: keine ahnugn
  start:
    description: starts lobby
  player:
    description: keine ahnung
  kickall:
    description: kickall to hub
  countdown:
    description: sets countdown to null
